# Generated by Django 6.0.1 on 2026-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrokeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Other', 'Другой')], max_length=10, verbose_name='Пол')),
                ('age', models.FloatField(verbose_name='Возраст')),
                ('hypertension', models.BooleanField(default=False, verbose_name='Гипертония (0-нет, 1-да)')),
                ('heart_disease', models.BooleanField(default=False, verbose_name='Болезни сердца')),
                ('ever_married', models.CharField(choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=5, verbose_name='Был ли в браке')),
                ('work_type', models.CharField(choices=[('Private', 'Частный сектор'), ('Self-employed', 'Самозанятый'), ('Govt_job', 'Госслужащий'), ('children', 'Ребенок'), ('Never_worked', 'Никогда не работал')], max_length=20, verbose_name='Тип работы')),
                ('residence_type', models.CharField(choices=[('Urban', 'Город'), ('Rural', 'Село')], max_length=10, verbose_name='Тип проживания')),
                ('avg_glucose_level', models.FloatField(verbose_name='Средний уровень глюкозы')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='Индекс массы тела (ИМТ)')),
                ('smoking_status', models.CharField(choices=[('formerly smoked', 'Ранее курил(а)'), ('never smoked', 'Никогда не курил(а)'), ('smokes', 'Курю'), ('Unknown', 'Неизвестно')], max_length=20, verbose_name='Статус курения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
