# Generated by Django 6.0.1 on 2026-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strokedata',
            name='ever_married',
            field=models.CharField(choices=[('Yes', 'Да'), ('No', 'Нет')], default='Нет', max_length=5, verbose_name='Был ли в браке'),
        ),
        migrations.AlterField(
            model_name='strokedata',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='Male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='strokedata',
            name='hypertension',
            field=models.BooleanField(default=False, verbose_name='Гипертония'),
        ),
        migrations.AlterField(
            model_name='strokedata',
            name='residence_type',
            field=models.CharField(choices=[('Urban', 'Город'), ('Rural', 'Село')], default='Город', max_length=10, verbose_name='Тип проживания'),
        ),
        migrations.AlterField(
            model_name='strokedata',
            name='smoking_status',
            field=models.CharField(choices=[('formerly smoked', 'Ранее курил(а)'), ('never smoked', 'Никогда не курил(а)'), ('smokes', 'Курю'), ('Unknown', 'Неизвестно')], default='Курю', max_length=20, verbose_name='Статус курения'),
        ),
        migrations.AlterField(
            model_name='strokedata',
            name='work_type',
            field=models.CharField(choices=[('Private', 'Частный сектор'), ('Self-employed', 'Самозанятый'), ('Govt_job', 'Госслужащий'), ('children', 'Ребенок'), ('Never_worked', 'Никогда не работал')], default='Никогда не работал', max_length=20, verbose_name='Тип работы'),
        ),
    ]
